spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enumdemo
    username: enumdemo
    password: enumdemo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?????? ??? ????; ? ????????? ? validate / none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: always
